config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :groups do
    get :numbers
  end

  root to: "groups#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :numbers, dependent: :destroy
  belongs_to :user, optional: true
  validates :title, presence: true
  validates :operation, presence: true
  validates :digits, presence: true
  validates :timer, presence: true
  validates :total, presence: true
end

app/models/number.rb
class Number < ApplicationRecord
  belongs_to :group
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :groups
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  # before_action :set_group, only: [:show, :edit, :update, :destroy]
  before_action :set_group, only: [:show, :destroy]
  before_action :authenticate_user!

  # GET /groups
  # GET /groups.json
  def index
    @groups = current_user.groups.order("created_at DESC")
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  # def edit
  # end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)
    @group.user_id = current_user.id
    respond_to do |format|
      if @group.save
        result = CreateNumbers.call(params: params, group: @group)
        if result.success?
          format.html { redirect_to groups_url, notice: 'Новая игра создано успешно!' }
          format.json { render result, status: :created}
          # format.html { redirect_to @group, notice: 'Group was successfully created.' }
          # format.json { render :show, status: :created, location: @group }
        else
          format.html { render :new }
          format.json { render json: @group.errors, status: :unprocessable_entity }
        end
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def numbers
    # @group = Group.find(params[:group_id])
    @numbers = Number.where(group_id: params[:group_id])
    @timer = Group.find(params[:group_id]).timer
    respond_to do |format|
      format.html
      format.json { render json: @numbers }
    end
    # render json: @numbers
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  # def update
  #   @group.user_id = current_user.id
  #   respond_to do |format|
  #     if @group.update(group_params)
  #       format.html { redirect_to @group, notice: 'Group was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @group }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @group.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:title, :operation, :digits, :timer, :total, :sum)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    {
      success: "alert-success",
      error: "alert-danger",
      alert: "alert-warning",
      notice: "alert-info"
    }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
  def set_operation(group)
    case group.operation
    when 0
      "сложение или вычитание"
    when 1
      "умножение"
    when 2
      "деление"
    end
  end
end

app/views/groups/_form.html.erb
<%= form_with(model: group, local: true) do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title, "Название" %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :operation, "Операция" %>&nbsp;&nbsp;&nbsp;&nbsp;
    <%#= form.number_field :operation %>
    <%#= form.select :operation, options_for_select(Group.operations.values, selected: params[:operation]), class: 'form-control' %>
    <%= form.select :operation, options_for_select(["сложение или вычитание", "умножение", "деление"], :selected => params[:operation], disabled: ["умножение", "деление"]), class: 'form-control' %>
  </div>
  

  <div class="form-group">
    <%= form.label :digits, "Количество цифр" %>
    <%= form.number_field :digits, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :timer, "Время перехода" %>
    <%= form.text_field :timer, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :total, "Количество номеров" %>
    <%= form.number_field :total, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%#= form.label :sum %>
    <%#= form.number_field :sum, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.submit "Создать", class: "btn btn-success btn-block" %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Show', @group %> |
<%= link_to 'Назад', groups_path %>

app/views/groups/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>Список</h1>
  </div>

  <div class="col-sm-6 text-right">
  <%= link_to new_group_path, class: 'btn btn-primary' do %>
    Создать новая игра
  <% end %>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover text-center">
    <thead>
      <tr>
        <th>Название</th>
        <th>Операция</th>
        <th>Количество цифр</th>
        <th>Время перехода</th>
        <th>Количество номеров</th>
        <!--<th>Sum</th>-->
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @groups.each do |group| %>
        <tr>
          <td><%= group.title %></td>
          <td><%= set_operation(group) %></td>
          <td><%= group.digits %></td>
          <td><%= group.timer %></td>
          <td><%= group.total %></td>
          <!--<td><%#= group.sum %></td>-->
          <td><%= link_to 'Начать', group_numbers_path(group.id), class: "btn btn-danger" %></td>
          <td><%= link_to 'Показать', group, class: "btn btn-info" %></td>
          <!--<td><%#= link_to 'Edit', edit_group_path(group) %></td>-->
          <td><%= link_to 'Удалить', group, method: :delete, data: { confirm: 'Вы уверены?' }, class: "btn btn-default" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/groups/new.html.erb
<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4">
    <%= render 'form', group: @group %>
    <%= link_to 'Назад', groups_path, class: "btn btn-primary btn-block" %>
  </div>
  <div class="col-md-4"></div>
</div>

app/views/groups/numbers.html.erb
<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-10">
    <div class="jumbotron">
      <div id="nums" class="container text-center"></div>
    </div>
  </div>
  <div class="col-md-1"></div>
</div>
<hr>
<!-- Button trigger modal -->
<div class="row">
    <div class="col-md-4">
      <%= link_to "Назад", groups_path, class: "btn btn-primary btn-block" %>
    </div>
    <div class="col-md-4">
      <button type="button" class="btn btn-info btn-block" data-toggle="modal" data-target="#myModal2">
        Показать как столбец 
      </button>
    </div>
    <div class="col-md-4">
      <button type="button" class="btn btn-success btn-block" data-toggle="modal" data-target="#myModal">
        Показать результат
      </button>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"></h4>
      </div>
      <div class="modal-body">
        <h1>Результат : <strong><%= @numbers.sum(:amount) %></strong></h1>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger btn-block" data-dismiss="modal">Закрыть</button>
        <!--<button type="button" class="btn btn-primary">Save changes</button>-->
      </div>
    </div>
  </div>
</div>
<br>

<!-- Modal -->
<div class="modal fade" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel2">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel2"></h4>
      </div>
      <div class="modal-body">
        <% @numbers.each do |n| %>
          <h1><%= n.amount%></h1>
        <% end %>
        <hr style="height:1px;border:none;color:#333;background-color:#333;">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger btn-block" data-dismiss="modal">Закрыть</button>
        <!--<button type="button" class="btn btn-primary">Save changes</button>-->
      </div>
    </div>
  </div>
</div>

<script>
  var numbers = [];
  var timer;
  timer = <%= @timer %>;
  numbers = <%= @numbers.pluck(:amount) %>;
  numbers.unshift("Поехали!");
  numbers.push("Конец");
  
  function show_numbers(array, delegate, delay) {
    array.forEach(function (el, i) {
      setTimeout(() => {
        delegate(array[i]);
      }, i * delay);
    });
  }

  function clear_numbers() {
    document.getElementById('nums').innerHTML = "";
  }

  show_numbers(numbers, function(obj) {
      clear_numbers();
      my_temp = document.getElementById('nums').innerHTML += '<h1>' + obj + '</h1>';
    }, timer * 1000);
  

  // console.log(numbers);
</script>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Название:</strong>
  <%= @group.title %>
</p>

<p>
  <strong>Операция:</strong>
  <%= @group.operation %>
</p>

<p>
  <strong>Количество цифр:</strong>
  <%= @group.digits %>
</p>

<p>
  <strong>Время перехода:</strong>
  <%= @group.timer %>
</p>

<p>
  <strong>Количество номеров:</strong>
  <%= @group.total %>
</p>
<!--
<p>
  <strong>Sum:</strong>
  <%#= @group.sum %>
</p>

<%#= link_to 'Edit', edit_group_path(@group) %> |-->
<%= link_to 'Back', groups_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MentalMath</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/notices' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<%# if user_masquerade? %>
  <!--<div class="alert alert-warning text-center">
    You're logged in as <b><%#= current_user.email %> (<%#= current_user.email %>)</b>
    <%#= link_to back_masquerade_path(current_user) do %><%#= icon("fas", "times") %> Logout <%# end %>
  </div>-->
<%# end %>

<nav class="navbar navbar-expand-md navbar-light bg-light">
  <div class="container">
    <%#= link_to Rails.configuration.application_name, root_path, class: "navbar-brand" %>
    <%= link_to "Ментальная Арифметика", root_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarMain" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarMain">
      <ul class="navbar-nav mr-auto mt-2 mt-md-0">
      </ul>

      <ul class="navbar-nav">
        <!--<li class="nav-item"><%#= link_to "What's New", announcements_path, class: "nav-link #{unread_announcements(current_user)}" %></li>
        <li class="nav-item"><%#= link_to "Все Машины", cars_path, class: "nav-link" %></li>
        <li class="nav-item"><%#= link_to "Все Отчёты", reports_path, class: "nav-link" %></li>-->
        <% if user_signed_in? %>
        <!--<li class="nav-item">
          <%#= link_to notifications_path, class: "nav-link" do %>
            <span><i class="fa fa-flag-o" aria-hidden="true"></i></span>
          <%# end %>
        </li>-->
          <%= link_to "Настройка", edit_user_registration_path, class: "nav-link" %>
          <%= link_to "Выход", destroy_user_session_path, method: :delete, class: "nav-link" %>
          <!--<li class="nav-item dropdown">
            <div id="nav-account-dropdown" class="dropdown-menu dropdown-menu-right" aria-labelledby="navbar-dropdown">
              <%# if current_user.admin? %>
                <%#= link_to "Admin Area", admin_root_path, class: "dropdown-item" %>
              <%# end %>
              <%#= link_to "Настройка", edit_user_registration_path, class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%#= link_to "Выход", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>-->

        <% else %>
          <li class="nav-item"><%= link_to "Регистрация", new_user_registration_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "Вход", new_user_session_path, class: "nav-link" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_notices.html.erb
<% flash.each do |msg_type, message| %>
  <div class="alert <%= bootstrap_class_for(msg_type) %>">
    <div class="container">
      <button class="close" data-dismiss="alert"><span>×</span></button>
      <%= message %>
    </div>
  </div>
<% end %>